#!/usr/bin/perl -w

use strict;

BEGIN {
use lib "/RAT";
}
use Tools::RatLed;
use Time::Out qw(timeout);

my $rulesFile='/etc/udev/rules.d/70-persistent-net.rules';
my $altresponse='No such device';
my $response='Cannot find device "wlan0"';
timeout 5 => sub {
system("cd /RAT/Tools; >nohup.out; nohup ifup wlan0 >Output.out 2>Error.err</dev/null &");
} ;
sleep(3);

my $checked = do {
    local $/ = undef;
open CHECK, "</RAT/Tools/nohup.out";        
    <CHECK>;
};


my $rules=<<PERSISTENT;
# Auto generated by RootStock-NG: setup_sdcard.sh
# udevadm info -q all -p /sys/class/net/eth0 --attribute-walk

# BeagleBone: net device ()
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"
PERSISTENT


        if ($checked =~/$altresponse|$response/)   {
							 	RatLed->SelfHeal();
								sleep (2); 
                                   	                        open FH1, ">$rulesFile";
                                                                print FH1 $rules;
                                                                close FH1; 
							 	sleep (2);	
								system("reboot");
}

system("nohup ifdown wlan0 >Output.out 2>Error.err</dev/null &");
exit;
